version: '3.8'

services:
  flask-api:
    image: wildfly8/flask-api
    container_name: flask-api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn app:app --bind 0.0.0.0:5000 --reload   
    ports:
      - 8000:5000
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=app.py
    networks:
      - flask-api     

networks:
  flask-api:
    name: flask-api      
