version: '3.8'

services:
  flask-api:
    image: wildfly8/flask-api
    container_name: flask-api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m gunicorn app:app --bind 0.0.0.0:5000 --reload"]    
    ports:
      - 8000:5000
      - 5678:5678
    volumes:
      - ./:/app      
    environment:
      - FLASK_APP=app.py
    networks:
      - flask-api
    stdin_open: true
    tty: true      

networks:
  flask-api:
    name: flask-api         
